import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
DB_URL = os.getenv("DB_URL")

UPWORK_AFFILIATE_ID = os.getenv("UPWORK_AFFILIATE_ID")
FREELANCER_AFFILIATE_ID = os.getenv("FREELANCER_AFFILIATE_ID")
FIVERR_AFFILIATE_ID = os.getenv("FIVERR_AFFILIATE_ID")
